/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mehadi hossain
 */
public class Field1 extends javax.swing.JFrame {

    /**
     * Creates new form Field1
     */
    public Field1() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/field.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1134, 700);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(473, 153, 150, 350);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);
        jButton2.setBounds(393, 223, 320, 210);

        jButton3.setText("jButton3");
        getContentPane().add(jButton3);
        jButton3.setBounds(493, 473, 100, 40);

        jButton4.setText("jButton4");
        getContentPane().add(jButton4);
        jButton4.setBounds(670, 283, 73, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
